In [51]:
import pandas as pd
import numpy as np
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [10]:
df = pd.read_csv("BRA.csv")

In [39]:
vocab = df['Home'].unique()

In [43]:
word2idx = {word: i for i, word in enumerate(vocab)}

In [48]:
def text_to_vector2(text): 
    text_vector = text.split(',')
    word_vector = np.zeros(len(text_vector), dtype=np.int_)
    for j in range(len(text_vector)):
        idx = word2idx.get(text_vector[j], None)
        if idx is None:
            continue
        else:
            word_vector[j] = idx
    return np.array(word_vector)

In [53]:
word_vectors2 = []
for _, row in df.iterrows():
    word_vectors2.append(text_to_vector2(row['Home'] + ',' + row['Away']))
    row['iHome'] = text_to_vector2(row['Home'] + ',' + row['Away'])

In [82]:
word_vectors2

[array([ 0, 12]),
 array([ 1, 11]),
 array([ 2, 13]),
 array([ 3, 17]),
 array([ 4, 18]),
 array([ 5, 15]),
 array([ 6, 14]),
 array([ 7, 16]),
 array([ 8, 10]),
 array([ 9, 19]),
 array([10,  6]),
 array([11,  5]),
 array([12,  9]),
 array([13,  8]),
 array([14,  4]),
 array([15,  3]),
 array([16,  1]),
 array([17,  7]),
 array([18,  2]),
 array([19,  0]),
 array([10, 19]),
 array([1, 0]),
 array([14,  7]),
 array([15, 12]),
 array([ 9, 13]),
 array([ 5, 17]),
 array([ 6, 11]),
 array([16, 18]),
 array([3, 8]),
 array([4, 2]),
 array([11, 15]),
 array([ 0, 14]),
 array([12, 10]),
 array([7, 9]),
 array([18,  5]),
 array([19,  4]),
 array([8, 1]),
 array([2, 6]),
 array([13,  3]),
 array([17, 16]),
 array([8, 2]),
 array([5, 3]),
 array([18, 12]),
 array([7, 1]),
 array([11, 16]),
 array([0, 9]),
 array([17, 14]),
 array([15, 10]),
 array([13, 19]),
 array([6, 4]),
 array([12, 17]),
 array([9, 8]),
 array([14, 13]),
 array([4, 0]),
 array([2, 7]),
 array([19, 11]),
 array([10, 18]),
 a